from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'icon3.png'

# Colors
PRIMARY_COLOR = '#ff80bf'
DARKER_PRIMARY_COLOR = '#ff4da6'
DARKEST_PRIMARY_COLOR = '#ff3399'

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 500